taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('api/v1/', include('tasks.api_urls')),  # Including the API routes

]

tasks/urls.py
from django.urls import path
from .views import register, user_login, user_logout, dashboard, mark_notification_as_read

app_name = "tasks"

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('', dashboard, name='dashboard'),
    path('notifications/<int:notification_id>/read/', mark_notification_as_read, name='mark_notification_as_read'),

]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver

class Task(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
    )
    title = models.CharField(max_length=200)
    description = models.TextField()
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='pending')
    due_date = models.DateTimeField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def is_overdue(self):
        if self.due_date and timezone.now() > self.due_date:
            return True
        return False

    @property
    def is_near_deadline(self):
        if self.due_date and (timezone.now() + timedelta(days=1)) > self.due_date and not self.is_overdue:
            return True
        return False

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='notifications')
    message = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"Notification for {self.user.username}: {self.message}"

tasks/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Task

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'status', 'due_date']
        widgets = {
            'due_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

tasks/views.py
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from .forms import RegistrationForm, LoginForm, TaskForm
from .models import Task
from django.core.paginator import Paginator
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
from .models import Notification
from django.shortcuts import redirect


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('tasks:login')
    else:
        form = RegistrationForm()
    return render(request, 'tasks/register.html', {'form': form})

def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('tasks:dashboard')
        else:
            messages.error(request, 'Invalid credentials')
    else:
        form = LoginForm()
    return render(request, 'tasks/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('tasks:login')

@login_required
def dashboard(request):
    notifications = Notification.objects.filter(user=request.user, read=False)
    print(request.user)
    return render(request, 'tasks/dashboard.html', {'notifications': notifications, "user_name":request.user})



def mark_notification_as_read(request, notification_id):
    try:
        # Fetch the notification and mark it as read
        notification = Notification.objects.get(id=notification_id, user=request.user)
        notification.read = True
        notification.save()
    except Notification.DoesNotExist:
        # Handle the error as you see fit
        pass
    return redirect('tasks:dashboard')  # Redirect back to the dashboard or wherever you're displaying notifications

tasks/templates/tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Manager</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Bootstrap CSS CDN -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'tasks:dashboard' %}">TaskManager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks:logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <span class="nav-link fas fa-user" id="username_id"> <span class="pl-1">{{ user_name }}</span></span>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS and jQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

tasks/templates/tasks/confirm_delete.html
{% extends "tasks/base.html" %}

{% block content %}
    <div class="container mt-5">
        <h2>Confirm Delete</h2>
        <p>Are you sure you want to delete task "{{ task.title }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes, Delete</button>
            <a href="{% url 'tasks:dashboard' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock %}

tasks/templates/tasks/dashboard.html
{% extends "tasks/base.html" %}
{% load static %}

{% block content %}

<div class="container mt-4">
    <h2>Your Tasks</h2>
    <div class="row mb-3">
        <div class="col-md-6">
            <div class="input-group">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="filter">Filter by:</label>
                </div>
                <select class="custom-select" id="filter" onchange="filterTasks(this.value)">
                    <option value="all" selected>All</option>
                    <option value="pending">Pending</option>
                    <option value="in_progress">In Progress</option>
                    <option value="completed">Completed</option>
                </select>
            </div>
        </div>
        
        <div class="col-md-6">
            <input type="text" class="form-control" id="search" placeholder="Search tasks..." onkeyup="searchTasks(this.value)">
        </div>
    </div>
    {% if notifications %}
    <div class="notifications">
        {% for notification in notifications %}
            <div class="notification">
                {{ notification.message }}
                <a href="{% url 'tasks:mark_notification_as_read' notification.id %}">Mark as read</a>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <button type="button" class="btn btn-success mb-3" data-toggle="modal" data-target="#addTaskModal">
        Add New Task
    </button>
     <!-- New row for sorting option -->
     <div class="row mb-2">
        <div class="col-md-6"></div> <!-- Empty left column to push the dropdown to the right -->
        <div class="col-md-6 text-right">
            <div class="input-group">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="sortOptions">Sort by:</label>
                </div>
                <select class="custom-select" id="sortOptions" onchange="sortTasks()">
                    <option value="title">Title</option>
                    <option value="status">Status</option>
                    <option value="created_at">Create TIme</option>
                    <option value="due_date">Due Date</option>
                </select>
            </div>
        </div>
    </div>
    <ul class="list-group" id="tasksList">
        <!-- This will be dynamically populated using JavaScript -->
    </ul>
<!-- Task Creation Modal -->
<div class="modal fade" id="addTaskModal" tabindex="-1" role="dialog" aria-labelledby="addTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addTaskModalLabel">Add New Task</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Task Creation Form -->
                <form id="addTaskForm">
                    <div class="form-group">
                        <label for="taskTitle">Task Title</label>
                        <input type="text" class="form-control" id="taskTitle" placeholder="Enter task title" required>
                    </div>
                    <div class="form-group">
                        <label for="taskDescription">Description</label>
                        <textarea class="form-control" id="taskDescription" rows="3" placeholder="Enter task description" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="taskStatus">Status</label>
                        <select class="form-control" id="taskStatus">
                            <option value="pending">Pending</option>
                            <option value="in_progress">In Progress</option>
                            <option value="completed">Completed</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="taskDueDate">Due Date</label>
                        <input type="datetime-local" class="form-control" id="taskDueDate">
                    </div>
                    <button type="submit" class="btn btn-primary" id="submit_btn">Add Task</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Read Only Task Details Modal -->
<div class="modal fade" id="taskDetailsModal" tabindex="-1" role="dialog" aria-labelledby="taskDetailsModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="taskDetailsModalLabel">Task Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <strong>Title:</strong> <span id="detailTitle"></span><br>
                <strong>Description:</strong> <span id="detailDescription"></span><br>
                <strong>Status:</strong> <span id="detailStatus"></span><br>
                <strong>Due Date:</strong> <span id="detailDueDate"></span><br>
            </div>
        </div>
    </div>
</div>




    <nav aria-label="Page navigation example" class="mt-4">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <button id="prevPage" onclick="changePage(-1)" class="page-link">Previous</button>
            </li>
            <li class="page-item disabled">
                <span class="page-link" id="currentPageDisplay">Page 1</span>
            </li>
            <li class="page-item">
                <button id="nextPage" onclick="changePage(1)" class="page-link">Next</button>
            </li>
        </ul>
    </nav>
</div>

<script type="text/javascript">
    var csrftoken = '{{ csrf_token }}';
</script>
<script src="{% static 'js/scripts.js' %}"></script>

{% endblock %}

tasks/templates/tasks/login.html
{% extends "tasks/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-5">
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <small class="d-block mt-2">Don't have an account? <a href="{% url 'tasks:register' %}">Register</a></small>
    </div>
{% endblock %}

tasks/templates/tasks/register.html
{% extends "tasks/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
{% endblock %}